############################################################
# CoCoNuT development dockerfile 
############################################################

# Set the base image to coconut:devenv
FROM zafeirakopoulos/coconut:devenv

LABEL maintainer "Zafeirakis Zafeirakopoulos" \
		version = "0.1" \
		description = "CoCoNuT development environment"

	 


